version: '3'
services:
  front:
    build:
      context: './react-ui'
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-networks
    volumes:
      - ./react-ui:/app
    depends_on:
      - backend

  backend:
    build:
      context: './Backend'
      dockerfile: Dockerfile
    ports:
      -8000:8000
    container_name: express-container
    networks:
      - mern-stack-networks
    volumes:
      - ./Backend:/app
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-networks
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=test